### PR TITLE
Disable wide band sample rate (hopefully fix bluetooth calling issues)

### PR DESCRIPTION
**Pull request by hunterzero99**
Change taken from an old [KB-Article here](https://forum.xda-developers.com/lineage/general/kb-article-troubleshooting-bluetooth-t3646969) / original reference Samsung [device patch here](https://review.lineageos.org/#/c/LineageOS/android_device_samsung_klte-common/+/178371/).  I'm struggling to figure out how to compile to test.

### CODE REVIEW

**Comment by firebird11** [comment]
did you try this locally ?

**Comment by hunterzero99** [comment]
I haven't been able to build a version of the ROM with the change in effect
(been trying for a few hours now but the build system is unfamiliar to me).

I'd be happy to try out a ROM if you have a simple way of trying to compile
with the change in place.

**Comment by hunterzero99** [comment]
I've been doing some reading, and I might be able to force it on in the build.prop --I'm going to give the changes there a try and will report back if it has any success.

**Comment by firebird11** [comment]
can you contact me on hangouts or telegram ?

**Comment by firebird11** [comment]
or try this build , it has the change you made
https://www.androidfilehost.com/?fid=746163614322269417

**Comment by hunterzero99** [comment]
Damn --it doesn't seem to make a difference.  Thank you for trying.  I'll
keep researching to see if I can make any headway.

**Comment by firebird11** [comment]
keep trying :)

**Pull request closed without merging**
